### ISSUE TITLE
Prune inactive committers

### ISSUE THREAD

**Issue by akurtakov** [eclipse-tycho/.eclipsefdn#4]
In the last 2 years there hasn't been contributions from:
* @jsievers  https://projects.eclipse.org/projects/technology.tycho/CM/jsievers
* maschreiber https://projects.eclipse.org/projects/technology.tycho/CM/maschreiber

Please state here whether you want to stay committer on the project. 
Retiring inactive committers will happen after July 3 2024 for people that haven't requested to remain such.

**Comment by netomi** [comment]
While the action to retire an inactive committer is perfectly fine, I believe the mean of communication is not correct. The EDP outlines explicitly how to retire a committer (announcing via the dev-list), see: https://www.eclipse.org/projects/handbook/#elections-retire-cm

Notifications get easily lost and there is no easy trace for other members / committers of the project on this matter imho.

@waynebeaton

**Comment by akurtakov** [comment]
@netomi Dev list announcement has been done yesterday via https://www.eclipse.org/lists/tycho-dev/msg02172.html

**Comment by akurtakov** [comment]
Both Martin and Jan retired now. Than you for all the work done during the years and maybe you will come back at some point!
